apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi-deployment
  labels:
    app: nodeapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapi
  template:
    metadata:
      labels:
        app: nodeapi
    spec:
      containers:
      - name: nodeserver
        image: elvirav/node-api:latest
        env:
        - name: MYSQL_DATABASE
          value: icecream
        - name: MYSQL_USER
          value: admin
        - name: MYSQLDB_PASSWORD
          value: elvira
        - name: MYSQL_ROOT_PASSWORD
          value: elvira
        - name: SERVICE_TAGS
          value: prod
        - name: SERVICE_NAME
          value: mysql
        - name: MYSQLDB_PORT
          value: '3306'
        - name: MYSQLDB_HOST
          value: mysql
        - name: MYSQLDB_USER
          value: admin
        - name: MYSQLDB_NAME
          value: icecream
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: nodeapi-service
  labels:
    app: nodeapi
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: nodeapi

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodeapi
spec:
  rules:
  - host: api.evargas.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nodeapi-service
            port:
              number: 80